include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "build/**"
    - "**/*.g.dart"

formatter:
  page_width: 140

linter:
  rules:
    prefer_expression_function_bodies: true
    prefer_single_quotes: true
    require_trailing_commas: true