include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - 'build/**'
    - '**/*.g.dart'
    - '**/*.gen.dart'
    - '**/*.mapper.dart'

formatter:
  page_width: 120
  trailing_commas: preserve

linter:
  rules:
    always_use_package_imports: true
    prefer_expression_function_bodies: true
    prefer_single_quotes: true
    require_trailing_commas: true