include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - 'build/**'
    - '**/*.g.dart'
    - '**/*.gen.dart'
    - '**/*.mapper.dart'

formatter:
  page_width: 120

linter:
  rules:
    prefer_expression_function_bodies: true
    prefer_single_quotes: true