name: state_tests
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0

  equatable: ^1.2.5

  binder: ^0.2.0

  bloc: ^6.1.0
  flutter_bloc: ^6.1.0

  flutter_command: ^0.9.3

  mobx: ^1.2.1+4
  flutter_mobx: ^1.1.0+2

  states_rebuilder: ^3.2.0

  redux: ^4.0.0+3
  flutter_redux: ^0.7.0
  redux_logging: ^0.4.0

  flutter_riverpod: ^0.12.1
  riverpod: ^0.12.1


  #preview: ^0.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.10.4
  mobx_codegen: ^1.1.1+3

flutter:
  uses-material-design: true

  assets:
    - assets/images/binder_logo.png
    - assets/images/bloc_logo.png
    - assets/images/cubit_logo.png
    - assets/images/command_logo.png
    - assets/images/mobx_logo.png
    - assets/images/rebuilder_logo.png
    - assets/images/redux_logo.png
    - assets/images/riverpod_logo.png