name: state_tests
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: "3.7.2"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  binder: ^0.4.0

  bloc: ^9.0.0
  flutter_bloc: ^9.1.0

  flutter_command: ^7.2.2

  get: ^4.7.2

  mobx: ^2.5.0
  flutter_mobx: ^2.3.0

  provider: ^6.1.2

  states_rebuilder: ^6.4.0

  redux: ^5.0.0
  flutter_redux: ^0.10.0
  redux_logging: ^0.5.1

  flutter_riverpod: ^2.6.1
  riverpod: ^2.6.1

  json_annotation: any

  dart_mappable: ^4.5.0

  collection: any
dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.13
  dart_mappable_builder: ^4.3.1+1
  flutter_lints: ^5.0.0
  flutter_gen_runner: 5.10.0
  json_serializable: any
  lints: ^5.1.1
  mobx_codegen: ^2.7.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/