name: state_tests
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <=3.7.2"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  equatable: ^2.0.7

  binder: ^0.4.0

  bloc: ^9.0.0
  flutter_bloc: ^9.1.0

  flutter_command: ^7.2.2

  get: ^4.7.2

  mobx: ^2.5.0
  flutter_mobx: ^2.3.0

  provider: ^6.1.2

  states_rebuilder: ^6.4.0

  redux: ^5.0.0
  flutter_redux: ^0.10.0
  redux_logging: ^0.5.1

  flutter_riverpod: ^2.6.1
  riverpod: ^2.6.1

  reflectable: ^4.0.12
  json_annotation: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.13
  mobx_codegen: ^2.7.0
  json_serializable: any

flutter:
  uses-material-design: true

  assets:
    - assets/images/binder_logo.png
    - assets/images/bloc_logo.png
    - assets/images/cubit_logo.png
    - assets/images/command_logo.png
    - assets/images/getx_logo.png
    - assets/images/mobx_logo.png
    - assets/images/rebuilder_logo.png
    - assets/images/redux_logo.png
    - assets/images/riverpod_logo.png