name: state_tests
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: "3.7.2"

dependencies:
  flutter:
    sdk: flutter
  bloc: ^9.0.0
  bloc_concurrency: ^0.3.0
  collection: any
  cupertino_icons: ^1.0.8
  dart_mappable: ^4.5.0
  flutter_bloc: ^9.1.0
  flutter_command: ^7.2.2
  flutter_hooks: ^0.21.2
  flutter_html: ^3.0.0
  flutter_mobx: ^2.3.0
  flutter_redux: ^0.10.0
  flutter_riverpod: ^2.6.1
  functional_widget_annotation: ^0.10.0
  get: ^4.7.2
  google_fonts: ^6.2.1
  hooks_riverpod: ^2.6.1
  json_annotation: any
  meta: ^1.15.0
  mobx: ^2.5.0
  provider: ^6.1.2
  states_rebuilder: ^6.4.0
  redux: ^5.0.0
  redux_logging: ^0.5.1
  riverpod_annotation: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.13
  dart_mappable_builder: ^4.3.1+1
  flutter_lints: ^5.0.0
  flutter_gen_runner: 5.10.0
  functional_widget: ^0.10.2
  json_serializable: any
  lints: ^5.1.1
  mobx_codegen: ^2.7.0
  riverpod_generator: ^2.6.3
  riverpod_lint: ^2.6.3

flutter:
  uses-material-design: true

  assets:
    - assets/images/