// This file has been generated by the reflectable package.
// https://github.com/dart-lang/reflectable.

import 'dart:core';
import 'package:flutter/src/widgets/framework.dart' as prefix2;
import 'package:flutter/src/widgets/image.dart' as prefix3;
import 'package:state_tests/common/StatePageEnum.dart' as prefix1;
import 'package:vnum/vnum.dart' as prefix0;

// ignore_for_file: prefer_adjacent_string_concatenation
// ignore_for_file: prefer_collection_literals
// ignore_for_file: unnecessary_const
// ignore_for_file: implementation_imports

// ignore:unused_import
import 'package:reflectable/mirrors.dart' as m;
// ignore:unused_import
import 'package:reflectable/src/reflectable_builder_based.dart' as r;
// ignore:unused_import
import 'package:reflectable/reflectable.dart' as r show Reflectable;

final _data = <r.Reflectable, r.ReflectorData>{
  const prefix0.VnumTypeReflectable(): r.ReflectorData(
      <m.TypeMirror>[
        r.GenericClassMirrorImpl(
            r'Vnum',
            r'vnum.Vnum',
            519,
            0,
            const prefix0.VnumTypeReflectable(),
            const <int>[0, 10, 11, 12, 14, 15, 16, 17, 18],
            const <int>[12, 19, 20, 14, 21, 11, 13],
            const <int>[10],
            -1,
            {r'allCasesFor': () => prefix0.Vnum.allCasesFor},
            {},
            {
              r'fromValue': (b) => (value, baseType) =>
                  b ? prefix0.Vnum.fromValue(value, baseType) : null,
              r'fromJson': (b) =>
                  (json) => b ? prefix0.Vnum.fromJson(json) : null
            },
            -1,
            -1,
            const <int>[-1],
            null,
            null,
            (o) => false,
            const <int>[2],
            0),
        r.NonGenericClassMirrorImpl(
            r'StatePageEnum',
            r'.StatePageEnum',
            7,
            1,
            const prefix0.VnumTypeReflectable(),
            const <int>[1, 2, 3, 4, 5, 6, 7, 8, 9, 22, 23, 24, 25, 35, 36, 37],
            const <int>[12, 19, 20, 14, 21, 22, 13, 23, 24, 25],
            const <int>[26, 27, 28, 29, 30, 31, 32, 33, 34],
            -1,
            {
              r'binder': () => prefix1.StatePageEnum.binder,
              r'bloc': () => prefix1.StatePageEnum.bloc,
              r'cubit': () => prefix1.StatePageEnum.cubit,
              r'command': () => prefix1.StatePageEnum.command,
              r'getX': () => prefix1.StatePageEnum.getX,
              r'mobX': () => prefix1.StatePageEnum.mobX,
              r'rebuilder': () => prefix1.StatePageEnum.rebuilder,
              r'redux': () => prefix1.StatePageEnum.redux,
              r'riverPod': () => prefix1.StatePageEnum.riverPod
            },
            {},
            {
              r'define': (b) => (fromValue) =>
                  b ? prefix1.StatePageEnum.define(fromValue) : null,
              r'': (b) => (value) => b ? prefix1.StatePageEnum(value) : null,
              r'fromJson': (b) =>
                  (json) => b ? prefix1.StatePageEnum.fromJson(json) : null
            },
            -1,
            -1,
            const <int>[-1],
            null,
            null),
        r.TypeVariableMirrorImpl(r'T', r'vnum.Vnum.T',
            const prefix0.VnumTypeReflectable(), -1, 0, null)
      ],
      <m.DeclarationMirror>[
        r.VariableMirrorImpl(r'value', 1029, 0,
            const prefix0.VnumTypeReflectable(), -1, -1, -1, null, null),
        r.VariableMirrorImpl(r'binder', 33941, 1,
            const prefix0.VnumTypeReflectable(), 1, 1, 1, null, null),
        r.VariableMirrorImpl(r'bloc', 33941, 1,
            const prefix0.VnumTypeReflectable(), 1, 1, 1, null, null),
        r.VariableMirrorImpl(r'cubit', 33941, 1,
            const prefix0.VnumTypeReflectable(), 1, 1, 1, null, null),
        r.VariableMirrorImpl(r'command', 33941, 1,
            const prefix0.VnumTypeReflectable(), 1, 1, 1, null, null),
        r.VariableMirrorImpl(r'getX', 33941, 1,
            const prefix0.VnumTypeReflectable(), 1, 1, 1, null, null),
        r.VariableMirrorImpl(r'mobX', 33941, 1,
            const prefix0.VnumTypeReflectable(), 1, 1, 1, null, null),
        r.VariableMirrorImpl(r'rebuilder', 33941, 1,
            const prefix0.VnumTypeReflectable(), 1, 1, 1, null, null),
        r.VariableMirrorImpl(r'redux', 33941, 1,
            const prefix0.VnumTypeReflectable(), 1, 1, 1, null, null),
        r.VariableMirrorImpl(r'riverPod', 33941, 1,
            const prefix0.VnumTypeReflectable(), 1, 1, 1, null, null),
        r.MethodMirrorImpl(r'allCasesFor', 4325394, 0, -1, 2, 3, null,
            const <int>[0], const prefix0.VnumTypeReflectable(), null),
        r.MethodMirrorImpl(r'toJson', 65538, 0, null, null, null, null,
            const <int>[], const prefix0.VnumTypeReflectable(), null),
        r.MethodMirrorImpl(r'==', 131074, 0, -1, 4, 4, null, const <int>[1],
            const prefix0.VnumTypeReflectable(), null),
        r.ImplicitGetterMirrorImpl(const prefix0.VnumTypeReflectable(), 0, 13),
        r.MethodMirrorImpl(r'hashCode', 131075, 0, -1, 5, 5, null,
            const <int>[], const prefix0.VnumTypeReflectable(), null),
        r.MethodMirrorImpl(r'', 128, 0, -1, 6, 0, null, const <int>[],
            const prefix0.VnumTypeReflectable(), null),
        r.MethodMirrorImpl(r'define', 128, 0, -1, 6, 0, null, const <int>[2],
            const prefix0.VnumTypeReflectable(), null),
        r.MethodMirrorImpl(r'fromValue', 1, 0, -1, 6, 0, null,
            const <int>[3, 4], const prefix0.VnumTypeReflectable(), null),
        r.MethodMirrorImpl(r'fromJson', 1, 0, -1, 6, 0, null, const <int>[5],
            const prefix0.VnumTypeReflectable(), null),
        r.MethodMirrorImpl(r'toString', 131074, null, -1, 7, 7, null,
            const <int>[], const prefix0.VnumTypeReflectable(), null),
        r.MethodMirrorImpl(r'noSuchMethod', 65538, null, null, null, null, null,
            const <int>[6], const prefix0.VnumTypeReflectable(), null),
        r.MethodMirrorImpl(r'runtimeType', 131075, null, -1, 8, 8, null,
            const <int>[], const prefix0.VnumTypeReflectable(), null),
        r.MethodMirrorImpl(r'toJson', 65538, 1, null, null, null, null,
            const <int>[], const prefix0.VnumTypeReflectable(), null),
        r.MethodMirrorImpl(r'statePage', 131074, 1, -1, 9, 9, null,
            const <int>[], const prefix0.VnumTypeReflectable(), null),
        r.MethodMirrorImpl(r'shortName', 131074, 1, -1, 7, 7, null,
            const <int>[], const prefix0.VnumTypeReflectable(), null),
        r.MethodMirrorImpl(r'image', 131074, 1, -1, 10, 10, null, const <int>[],
            const prefix0.VnumTypeReflectable(), null),
        r.ImplicitGetterMirrorImpl(const prefix0.VnumTypeReflectable(), 1, 26),
        r.ImplicitGetterMirrorImpl(const prefix0.VnumTypeReflectable(), 2, 27),
        r.ImplicitGetterMirrorImpl(const prefix0.VnumTypeReflectable(), 3, 28),
        r.ImplicitGetterMirrorImpl(const prefix0.VnumTypeReflectable(), 4, 29),
        r.ImplicitGetterMirrorImpl(const prefix0.VnumTypeReflectable(), 5, 30),
        r.ImplicitGetterMirrorImpl(const prefix0.VnumTypeReflectable(), 6, 31),
        r.ImplicitGetterMirrorImpl(const prefix0.VnumTypeReflectable(), 7, 32),
        r.ImplicitGetterMirrorImpl(const prefix0.VnumTypeReflectable(), 8, 33),
        r.ImplicitGetterMirrorImpl(const prefix0.VnumTypeReflectable(), 9, 34),
        r.MethodMirrorImpl(r'define', 128, 1, -1, 1, 1, null, const <int>[7],
            const prefix0.VnumTypeReflectable(), null),
        r.MethodMirrorImpl(r'', 1, 1, -1, 1, 1, null, const <int>[8],
            const prefix0.VnumTypeReflectable(), null),
        r.MethodMirrorImpl(r'fromJson', 1, 1, -1, 1, 1, null, const <int>[9],
            const prefix0.VnumTypeReflectable(), null)
      ],
      <m.ParameterMirror>[
        r.ParameterMirrorImpl(
            r'object',
            16390,
            10,
            const prefix0.VnumTypeReflectable(),
            null,
            null,
            null,
            null,
            null,
            null,
            null),
        r.ParameterMirrorImpl(
            r'o',
            16390,
            12,
            const prefix0.VnumTypeReflectable(),
            null,
            null,
            null,
            null,
            null,
            null,
            null),
        r.ParameterMirrorImpl(
            r'value',
            6,
            16,
            const prefix0.VnumTypeReflectable(),
            null,
            -1,
            -1,
            null,
            null,
            null,
            null),
        r.ParameterMirrorImpl(
            r'value',
            6,
            17,
            const prefix0.VnumTypeReflectable(),
            null,
            -1,
            -1,
            null,
            null,
            null,
            null),
        r.ParameterMirrorImpl(
            r'baseType',
            16390,
            17,
            const prefix0.VnumTypeReflectable(),
            null,
            null,
            null,
            null,
            null,
            null,
            null),
        r.ParameterMirrorImpl(
            r'json',
            16390,
            18,
            const prefix0.VnumTypeReflectable(),
            null,
            null,
            null,
            null,
            null,
            null,
            null),
        r.ParameterMirrorImpl(
            r'invocation',
            32774,
            20,
            const prefix0.VnumTypeReflectable(),
            -1,
            11,
            11,
            null,
            null,
            null,
            null),
        r.ParameterMirrorImpl(
            r'fromValue',
            32774,
            35,
            const prefix0.VnumTypeReflectable(),
            -1,
            7,
            7,
            null,
            null,
            null,
            null),
        r.ParameterMirrorImpl(
            r'value',
            32774,
            36,
            const prefix0.VnumTypeReflectable(),
            -1,
            7,
            7,
            null,
            null,
            null,
            null),
        r.ParameterMirrorImpl(
            r'json',
            16390,
            37,
            const prefix0.VnumTypeReflectable(),
            null,
            null,
            null,
            null,
            null,
            null,
            null)
      ],
      <Type>[
        prefix0.Vnum,
        prefix1.StatePageEnum,
        const m.TypeValue<List<prefix0.Vnum<dynamic>>>().type,
        List,
        bool,
        int,
        const r.FakeType(r'vnum.Vnum<T*>'),
        String,
        Type,
        prefix2.Widget,
        prefix3.Image,
        Invocation
      ],
      2,
      {
        r'==': (dynamic instance) => (x) => instance == x,
        r'toString': (dynamic instance) => instance.toString,
        r'noSuchMethod': (dynamic instance) => instance.noSuchMethod,
        r'hashCode': (dynamic instance) => instance.hashCode,
        r'runtimeType': (dynamic instance) => instance.runtimeType,
        r'toJson': (dynamic instance) => instance.toJson,
        r'value': (dynamic instance) => instance.value,
        r'statePage': (dynamic instance) => instance.statePage,
        r'shortName': (dynamic instance) => instance.shortName,
        r'image': (dynamic instance) => instance.image
      },
      {},
      null,
      [])
};

final _memberSymbolMap = null;

void initializeReflectable() {
  r.data = _data;
  r.memberSymbolMap = _memberSymbolMap;
}
